---
    
- name: Downloading Log4j Jar 
  maven_artifact:
    group_id: log4j
    artifact_id: log4j
    version: 1.2.17
    repository_url: http://repo1.maven.org/maven2
    dest: "{{home_path}}/log_server/log4j.jar"

- name: Copy Chord log4j Server Properties
  template:
    force: yes
    src: "templates/log4j.Chord.properties"
    dest: "{{home_path}}/log_server/log4j.Chord.properties"
    mode: 0700

- name: Copy KeyStore log4j Server Properties
  template:
    force: yes
    src: "templates/log4j.KeyStore.properties"
    dest: "{{home_path}}/log_server/log4j.KeyStore.properties"
    mode: 0700

- name: Copy Analysis log4j Server Properties
  template:
    force: yes
    src: "templates/log4j.Analysis.properties"
    dest: "{{home_path}}/log_server/log4j.Analysis.properties"
    mode: 0700

- name: Check If log Servers are running
  shell: ps -ax
  register: log_server

- name: Start Chord logging server
  shell: "{{ item }}"
  with_items:
    - nohup java -classpath log4j.jar org.apache.log4j.net.SimpleSocketServer 4712 log4j.Chord.properties </dev/null >/dev/null 2>&1 &
  args:
   chdir: "{{home_path}}/log_server/"
  when: "log_server.stdout.find('log4j.Chord.properties') == -1"

- name: Start KeyStore logging server
  shell: "{{ item }}"
  with_items:
    - nohup java -classpath log4j.jar org.apache.log4j.net.SimpleSocketServer 4713 log4j.KeyStore.properties </dev/null >/dev/null 2>&1 &
  args:
   chdir: "{{home_path}}/log_server/"
  when: "log_server.stdout.find('log4j.KeyStore.properties') == -1"

- name: Start Analysis logging server
  shell: "{{ item }}"
  with_items:
    - nohup java -classpath log4j.jar org.apache.log4j.net.SimpleSocketServer 4713 log4j.Analysis.properties </dev/null >/dev/null 2>&1 &
  args:
   chdir: "{{home_path}}/log_server/"
  when: "log_server.stdout.find('log4j.Analysis.properties') == -1"